import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="p-3 border-b flex gap-4 text-sm">
          <a href="/" className="underline">Home</a>
          <a href="/dashboard" className="underline">Dashboard</a>
          <a href="/itinerary" className="underline">Itinerary</a>
          <a href="/catalog" className="underline">Catalog</a>
          <a href="/my-cabin" className="underline">My Cabin</a>
          <a href="/login" className="underline">Login</a>
          <a href="/docs" className="underline">API Docs</a>
          <a href="/users" className="underline">Users</a>
          <a href="/cabins" className="underline">Cabins</a>
        </nav>
        <main className="p-4">
          <Providers>
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
